# -*- coding: utf-8 -*-
"""cv lab-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSqFuWbZz6yKZr8eS8Aa9kx4RopF1TGU
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

#Function to display image
def show_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  #Original images
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title("original grayscale image")
  plt.axis('off')
  #3*3 kernel
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title("3*3")
  plt.axis('off')
  #5*5 kernel
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title("5*5 ")
  plt.axis('off')
  #7*7 kernel
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title("7*7")
  plt.axis('off')
  plt.show()

  plt.tight_layout()
  plt.show()

#read image 1 in grayscle
img =cv2.imread('/content/noisy image',0)
if img is None:
  print("Error: Image not found")
else:
  kernel_3x3=np.ones((3,3),np.float32)/9
  kernel_5x5=np.ones((5,5),np.float32)/25
  kernel_7x7=np.ones((7,7),np.float32)/49
  blur_3=cv2.filter2D(img,-1,kernel_3x3)
  blur_5=cv2.filter2D(img,-1,kernel_5x5)
  blur_7=cv2.filter2D(img,-1,kernel_7x7)
  show_comparison(img,blur_3,blur_5,blur_7)

#read image 1 in grayscle
img =cv2.imread('/content/panda',0)
if img is None:
  print("Error: Image not found")
else:
  kernel_3x3=np.ones((3,3),np.float32)/9
  kernel_5x5=np.ones((5,5),np.float32)/25
  kernel_7x7=np.ones((7,7),np.float32)/49
  blur_3=cv2.filter2D(img,-1,kernel_3x3)
  blur_5=cv2.filter2D(img,-1,kernel_5x5)
  blur_7=cv2.filter2D(img,-1,kernel_7x7)
  show_comparison(img,blur_3,blur_5,blur_7)

